### PR TITLE
Maxime roy/sandbox

### PR DESCRIPTION
**Pull request by maximeroycrim**
@JeremyFyke  and @matprov  ready to test the behaviour

### CODE REVIEW

**Comment by JeremyFyke** [comment]
Hi @maximeroycrim, this looks much nicer in terms of data organization, thank you!  And the new .json schema in the `*_v2.json` files is nice and definitely good from my perspective and should be made official (if @matprov agrees).  I like the `"eng"` and `"fr"` additions and also the `class DstEnum' which I *think* is intended to make the code less error-prone..?

A few minor additional suggestions (sorry if you are already have these on your radar):

- move `data/images` directory from data to `data/general/`
- move `data/disclaimer.txt` from data to `data/general/`
- if @matprov agrees, rebuild the full .json files using your new schema (instead of the v2 'demonstration' files).

**Comment by JeremyFyke** [comment]
Also, I'm happy to have this work merged to main, again if @matprov agrees.  It looks like you did all your work in plain .py file.  I think I need to switch over to using plain .py files moving forward (and get my team to do the same).   Does that make sense to you..?

**Comment by maximeroycrim** [comment]
@JeremyFyke, about plain .py for me it's easier to debug, you can discuss it with @matprov. Otherwise for the other comments, I agree with the changes you proposed. From now on, one of my colleagues (Antoine Daigneault-Demers) will take care of the next tasks

**Comment by matprov** [comment]
@maximeroycrim In order to get this PR merged we need the ipynb file to be committed. We can't diff a py with a ipynb and can't see the changes made to the notebook. Also, before committing, please make sure the app works as expected after the modifications you've made to the notebook.

@JeremyFyke We currently don't have a strong ipynb/py preference as it's more for convenience that we use notebook for now. But for now, let's continue in the notebook as stated before and keep the py for better PR reviews. This notebook will be easy to convert to py later on so let's focus at the right things for now.

**Comment by maximeroycrim** [comment]
@matprov, can you tell me how I can reproduce the bad behavior of the application ?  I will make the changes in the ipynb. There was a miscommunication I believe, because I had understood that developing in the .py would be easier

**Comment by matprov** [comment]
> @matprov, can you tell me how I can reproduce the bad behavior of the application ? I will make the changes in the ipynb. There was a miscommunication I believe, because I had understood that developing in the .py would be easier

@maximeroycrim 
Which bad behaviour do you refer to?
We have been clear on the fact that we keep working on the ipynb file until we agree to change. 
So please commit the notebook version of the modifications you've made in the scope of this pull request as comparing an ipynb with a py will be cumbersome for no reason.

**Pull request closed without merging**
