### PR TITLE
Changed debug flag to false (fixes final presentation style)

### PR DESCRIPTION
**Pull request by JeremyFyke**

### CODE REVIEW

**Comment by JeremyFyke** [comment]
hi @matprov - this is a simple pull request to fix the ugly progressbar issue you highlighted.

**Review by matprov — APPROVED** [review]

**Comment by matprov** [comment]
@JeremyFyke Accepted, you can merge when ready.

**Comment by JeremyFyke** [comment]
Hi @matprov - in prep for tomorrow's show and tell with Building Module group, could you update deployed app with this latest merge?  FYI the personal computer I used to test the container just died so I'm temporarily unable to test-run docker images locally.

**Comment by matprov** [comment]
Hi @JeremyFyke, it's updated. Let me know if you need to update something before tomorrow's presentation and i'll update it as well.

**Pull request merged**
